// Generated by CoffeeScript 1.4.0

(function() {

  describe("Something", function() {
    return it("should should be reasonable", function() {
      return expect(true).toBe(true);
    });
  });

}).call(this);

  describe("Make deck", function(){
    return it("should create a 52 card deck", function(){
      makeDeck()
      return expect(deck.length).toEqual(52);
    });
  });
